---
- name: "Chocolatey"
  hosts: wins
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present

    - name: Install adobe reader and pin
      win_chocolatey:
          name: adobereader
          state: present
          pinned: yes
